[window]
opacity = 1
startup_mode = "Fullscreen"
[font]

size = 14.0

[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"

[terminal]
shell = "zellij"
[general]
import = ["~/arch_dotfiles/alacritty/.config/alacritty/themes/themes/tokyo_night_storm.toml" ]
