return {
	"marko-cerovac/material.nvim",
	"oahlen/iceberg.nvim",
	"morhetz/gruvbox",
	"rose-pine/neovim",
	"rebelot/kanagawa.nvim",
	"atmosuwiryo/vim-winteriscoming",
	"oxfist/night-owl.nvim",
	"scottmckendry/cyberdream.nvim",
	{
		"getomni/neovim",
    		name = "omni",
	},
	{
		"catppuccin/nvim",
		name = "catppuccin",
	},
	"blazkowolf/gruber-darker.nvim",
	"Mofiqul/dracula.nvim",
	"tiagovla/tokyodark.nvim",
	"nyoom-engineering/oxocarbon.nvim",
	"jacoborus/tender.vim",
	"tyrannicaltoucan/vim-deep-space",
	"pineapplegiant/spaceduck",
	"sainnhe/edge",
	"loctvl842/monokai-pro.nvim",
	"vyrx-dev/void.nvim",
	"tomasr/molokai",
	"rakr/vim-one",
	"mhartington/oceanic-next",
	{
		"EdenEast/nightfox.nvim",
		lazy = false,
		priority = 1000,
		config = function()
		    local themes = {
			"material-palenight",
			"material-oceanic",
			"material-deep-ocean",
			"material-darker",
			"rose-pine-moon",
			"kanagawa",
			"kanagawa-wave",
			"WinterIsComing-dark-color-theme",
			"night-owl",
			"cyberdream",
			"omni",
			"catppuccin",
			"gruber-darker",
			"dracula",
			"tokyodark",
			"oxocarbon",
			"tokyonight-night",
			"tokyonight-storm",
			"gruvbox",
			"tender",
			"deep-space",
			"edge",
			"monokai-pro-classic",
			"monokai-pro-machine",
			"monokai-pro-octagon",
			"monokai-pro-ristretto",
			"monokai-pro-spectrum",
			"void",
			"molokai",
			"one",
			"OceanicNext",
		    }
		    math.randomseed(os.time())
		    local random_theme = themes[math.random(#themes)]
		    vim.cmd("colorscheme " .. random_theme)
		end,
	},
}
