return {
        "zaldih/themery.nvim",
        lazy = false,
        config = function()
	    require("themery").setup({
	      themes = {
			"material-palenight",
			"material-oceanic",
			"material-deep-ocean",
			"material-darker",
			"rose-pine-moon",
			"kanagawa",
			"kanagawa-wave",
			"WinterIsComing-dark-color-theme",
			"night-owl",
			"cyberdream",
			"omni",
			"catppuccin",
			"gruber-darker",
			"dracula",
			"tokyodark",
			"oxocarbon",
			"tokyonight-night",
			"tokyonight-storm",
			"gruvbox",
			"tender",
			"deep-space",
			"edge",
			"monokai-pro-classic",
			"monokai-pro-machine",
			"monokai-pro-octagon",
			"monokai-pro-ristretto",
			"monokai-pro-spectrum",
			"void",
			"molokai",
			"one",
			"OceanicNext",
			"vaporwave",
			"onedark",
			"onedark_vivid",
			"onedark_dark",
	},
	      livePreview = true,
	    })
        end
}
