
vim.pack.add({
	{src = "https://github.com/zaldih/themery.nvim.git"},
	{src = "https://github.com/marko-cerovac/material.nvim"},
	{src = "https://github.com/oahlen/iceberg.nvim"},
	{src = "https://github.com/pineapplegiant/spaceduck"},
	{src = "https://github.com/morhetz/gruvbox"},
	{src = "https://github.com/rose-pine/neovim", name = "rose-pine"},
	{src = "https://github.com/rebelot/kanagawa.nvim"},
	{src = "https://github.com/atmosuwiryo/vim-winteriscoming"},
	{src = "https://github.com/oxfist/night-owl.nvim"},
	{src = "https://github.com/scottmckendry/cyberdream.nvim"},
	{src = "https://github.com/raphamorim/lucario"},
	{src = "https://github.com/sainnhe/sonokai"},
	{src = "https://github.com/getomni/neovim", name = "getomni"},
	{src = "https://github.com/catppuccin/nvim"},
	{src = "https://github.com/blazkowolf/gruber-darker.nvim"},
	{src = "https://github.com/Mofiqul/dracula.nvim"},
	{src = "https://github.com/folke/tokyonight.nvim"},
	{src = "https://github.com/tiagovla/tokyodark.nvim"},
	{src = "https://github.com/nyoom-engineering/oxocarbon.nvim"},
	{src = "https://github.com/jacoborus/tender.vim"},
	{src = "https://github.com/tyrannicaltoucan/vim-deep-space"},
	{src = "https://github.com/pineapplegiant/spaceduck"},
	{src = "https://github.com/sainnhe/edge"},
	{src = "https://github.com/loctvl842/monokai-pro.nvim"},
	{src = "https://github.com/vyrx-dev/void.nvim"},
	{src = "https://github.com/tomasr/molokai"},
	{src = "https://github.com/rakr/vim-one"},
	{src = "https://github.com/mhartington/oceanic-next"},
	{src = "https://github.com/olimorris/onedarkpro.nvim"},
	{src = "https://github.com/srcery-colors/srcery-vim"},
})
 local my_themes = {
			"lucario",
			"spaceduck",
			"srcery",
			"sonokai",
			"material-palenight",
			"material-oceanic",
			"material-deep-ocean",
			"material-darker",
			"rose-pine-moon",
			"kanagawa",
			"kanagawa-wave",
			"WinterIsComing-dark-color-theme",
			"night-owl",
			"cyberdream",
			"omni",
			"catppuccin",
			"gruber-darker",
			"dracula",
			"tokyodark",
			"oxocarbon",
			"tokyonight-night",
			"tokyonight-storm",
			"gruvbox",
			"tender",
			"deep-space",
			"edge",
			"monokai-pro-classic",
			"monokai-pro-machine",
			"monokai-pro-octagon",
			"monokai-pro-ristretto",
			"monokai-pro-spectrum",
			"void",
			"molokai",
			"one",
			"OceanicNext",
			"vaporwave",
			"onedark",
			"onedark_vivid",
			"onedark_dark",
		}
require("themery").setup({
	themes = my_themes,
	livePreview = true,
})
